files:
  - source: /peachjam/locale/en/LC_MESSAGES/django.po
    translation: /peachjam/locale/%two_letters_code%/LC_MESSAGES/%original_file_name%

  - source: /africanlii/locale/en/LC_MESSAGES/django.po
    translation: /africanlii/locale/%two_letters_code%/LC_MESSAGES/%original_file_name%

  - source: /liiweb/locale/en/LC_MESSAGES/django.po
    translation: /africanlii/locale/%two_letters_code%/LC_MESSAGES/%original_file_name%

  - source: /lawlibrary/locale/en/LC_MESSAGES/django.po
    translation: /africanlii/locale/%two_letters_code%/LC_MESSAGES/%original_file_name%

  - source: /peachjam/js/locale/en/translation.json
    translation: /peachjam/js/locale/%two_letters_code%/%original_file_name%
