name: Build

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    name: Compile javascript and commit changes
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install dependencies
        run: npm ci --no-audit --prefer-offline --ignore-scripts

      - name: Build
        run: npx webpack --mode production

      - name: Push
        uses: EndBug/add-and-commit@v7
        with:
          add: 'peachjam/static/js/*app-prod.js --force'
          message: 'Update compiled javascript'
