name: Deploy

on:
  push:
    branches: [ main ]

jobs:
  deploy-agp:
    name: Deploy to agp.africanlii.org
    runs-on: ubuntu-latest
    concurrency: agp.africanlii.org
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: git push to agp.africanlii.org
      uses: dokku/github-action@master
      with:
        ssh_private_key: ${{ secrets.SSH_DEPLOYMENT_KEY }}
        git_remote_url: 'ssh://dokku@liiweb.africanlii.org:22/agp'
        git_push_flags: '--force'

  deploy-lawlibrary:
    name: Deploy to lawlibrary
    runs-on: ubuntu-latest
    concurrency: lawlibrary.org.za
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: git push to lawlibrary.org.za
      uses: dokku/github-action@master
      with:
        ssh_private_key: ${{ secrets.SSH_DEPLOYMENT_KEY }}
        git_remote_url: 'ssh://dokku@web2.laws.africa:22/lawlibrary'
        git_push_flags: '--force'

  deploy-senlii:
    name: Deploy to senlii
    runs-on: ubuntu-latest
    concurrency: senlii.org
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: git push to senlii.org
        uses: dokku/github-action@master
        with:
          ssh_private_key: ${{ secrets.SSH_DEPLOYMENT_KEY }}
          git_remote_url: 'ssh://dokku@web2.laws.africa:22/senlii'
          git_push_flags: '--force'
